- name: Backup existing PKI from frontends
  hosts:
    - frontends_a1
    - frontends_a2
    - frontends_c1
    - frontends_c2
  remote_user: root

  tasks:
    - name: Check if host has secrets
      stat:
        path: desec-ns/openvpn-client/secrets
      register: secrets
    - name: Fetch private key
      fetch:
        src: desec-ns/openvpn-client/secrets/client.key
        dest: pki-backup/
      when: secrets.stat.exists
    - name: Fetch public key
      fetch:
        src: desec-ns/openvpn-client/secrets/client.crt
        dest: pki-backup/
      when: secrets.stat.exists
    - name: Fetch ca certificate
      fetch:
        src: desec-ns/openvpn-client/secrets/ca.crt
        dest: pki-backup/
      when: secrets.stat.exists
    - name: Fetch TA key
      fetch:
        src: desec-ns/openvpn-client/secrets/ta.key
        dest: pki-backup/
      when: secrets.stat.exists

- name: Backup existing PKI from stack
  hosts: stack
  remote_user: root

  tasks:
    - name: Check if stack has secrets
      stat:
        path: desec-stack/openvpn-server/secrets
      register: secrets
    - name: Fetch private key
      fetch:
        src: desec-stack/openvpn-server/secrets/server.key
        dest: pki-backup/
      when: secrets.stat.exists
    - name: Fetch public key
      fetch:
        src: desec-stack/openvpn-server/secrets/server.crt
        dest: pki-backup/
      when: secrets.stat.exists
    - name: Fetch CA cert
      fetch:
        src: desec-stack/openvpn-server/secrets/ca.crt
        dest: pki-backup/
      when: secrets.stat.exists
    - name: Fetch TA key
      fetch:
        src: desec-stack/openvpn-server/secrets/ta.key
        dest: pki-backup/
      when: secrets.stat.exists
