- name: Restart Stack VPN
  hosts: stack
  remote_user: root

  tasks:
    - name: Restart OpenVPN container
      community.general.docker_compose:
        project_src: desec-stack
        restarted: yes
        services: openvpn-server

- name: Restart Frontends VPN
  hosts:
    - frontends_a1
    - frontends_a2
    - frontends_c1
    - frontends_c2
  remote_user: root

  tasks:
    - name: Restart OpenVPN container
      community.general.docker_compose:
        project_src: desec-ns
        restarted: yes
        services: openvpn-client
