- name: Restart Stack VPN
  hosts: stack
  remote_user: root

  tasks:
    - name: Restart OpenVPN container
      command:
        cmd: 'docker compose restart openvpn-server'
        chdir: desec-stack

- name: Restart Frontends VPN
  hosts:
    - frontends
  remote_user: root

  tasks:
    - name: Restart OpenVPN container
      command:
        cmd: 'docker-compose restart openvpn-client'
        chdir: desec-ns
