- name: Start Frontends
  hosts:
    - frontends_a1
    - frontends_a2
    - frontends_c1
    - frontends_c2
  remote_user: root

  tasks:
    - name: Start frontend
      community.general.docker_compose:
        project_src: desec-ns
        state: present
